### ISSUE TITLE
.idea to .gitignore

### ISSUE THREAD

**Issue by erayaydin** [semihsipahi/hpt-taskman#11]
`.idea` folder should be in `.gitignore` file

**Comment by semihsipahi** [comment]
okey this issue completed.

**Comment by erayaydin** [comment]
Also .idea folder should be deleted in repository with `git rm --cached -r .idea`

**Comment by semihsipahi** [comment]
i not understand =(

**Comment by erayaydin** [comment]
Şuan depoda .idea klasörü bulunuyor, onun silinmesi gerek (sadece depodan, localde kalmaya devam edecek). Ben silip PR olarak gönderiyim boş bir vakitte.

**Comment by erayaydin** [comment]
PR submitted #14

**Comment by semihsipahi** [comment]
merged =) thank u =)

**Comment by erayaydin** [comment]
You welcome :+1: **Nice project, I will contribute soon**

**Comment by semihsipahi** [comment]
I opened a new issues,we can development on their
