### ISSUE TITLE
Tasks statuses

### ISSUE THREAD

**Issue by sametcilli** [semihsipahi/hpt-taskman#17]
Tasks statuses should not be only active and completed.
Open and close could be. 
The task can closed. The reason is The task Could be completed, rejected,canceled,updated, etc

**Comment by semihsipahi** [comment]
thank you =) but,

We have an "action" in the name of the entity object models.
"tm_actions" income is equivalent to the table in the database.

it in "Ata","Başlandı","Devam Ediyor","Test","Tamanlandı" etc field avaible.

**Comment by semihsipahi** [comment]
thats way closed issue =)
